name: 'test my project'
on:
  push:
    branches:
      - pipe
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install -r requirements.txt 
          pipenv install --dev --ignore-pipfile
      - name: Run app
        run: |
          chmod +x st.sh
          ./st.sh


#
